In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [10]:
df = pd.read_csv('cardata.csv')

In [11]:
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82
5    115        2         8.0    10

In [12]:
df.experience

0     5.0
1    13.0
2     4.0
3     NaN
4     3.0
5     8.0
Name: experience, dtype: float64

In [17]:
exm_fit= df. experience .median()

In [18]:
exm_fit

5.0

In [19]:
df.experience= df.experience.fillna(exm_fit)

In [20]:
df.experience

0     5.0
1    13.0
2     4.0
3     5.0
4     3.0
5     8.0
Name: experience, dtype: float64

In [21]:
df

   speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10

In [22]:
reg=linear_model.LinearRegression()

In [25]:
reg.fit(df[['speed','car_age','experience']],df.risk)

LinearRegression()

In [26]:
reg.predict([[160,10,5]])

D:\Python Anaconda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([71.37146872])

In [28]:
reg.coef_

array([ 0.33059217,  1.61053246, -6.20772074])

In [29]:
reg.intercept_

np.float64(33.41000091043586)

In [30]:
0.33059217*160 + 1.61053246*10 + 5*-6.20772074 + 33.41000091043586

71.37146901043587